GROQ_API_KEY = "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"
QDRANT_URL = "https://7f878b41-88d0-4c3b-b25d-86a5aa04612a.us-east4-0.gcp.cloud.qdrant.io:6333"
QDRANT_KEY = "l7Kx-27jjy6rH0Bd6L5yOzFNzU-AS--E8f-xKrEXUwmuD7x2zmMILQ"

# LANGSMITH_TRACING=True
LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY="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"
LANGSMITH_PROJECT="pr-new-mesenchyme-9"
# OPENAI_API_KEY="<your-openai-api-key>"
ELEVENLAB_API_KEY="sk_eaf6096f9230681058c5890f1de2d1b1577f2c8e94852a93"
TAVILY_API_KEY="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"
OPENAI_API_KEY="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"
YOUTUB_API_KEY="AIzaSyChHqpzh0m34PHsRYfRp4dGC92YPFFgbks"  # Replace with your actual API key"
